# --------------------------------------------------------------
# Description:
# Post GitHub Changelog Blog Updates to Slack
# Triggers: Every Sunday at midnight (UTC) and manual dispatch.
# --------------------------------------------------------------

name: Post GitHub Changelog to Slack

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Download artifact # Download previous artifact to check for repeats
        uses: actions/download-artifact@v4
        with:
          name: artifact-file
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser slack-sdk requests python-dotenv
      - name: Run Python Slack bot script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          WORKFLOW_NAME: ${{ secrets.WORKFLOW_NAME }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          REPO_OWNER: ${{secrets.REPO_OWNER}}

        run: |
          python fetch_changelog.py || exit 1
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-file
          path: artifact-file.txt
